### ISSUE TITLE
Enable HTML in closed location info field

### ISSUE THREAD

**Issue by adambard1** [streetlives/yourpeer.nyc#183]
HI @shakilhossain1 if this is trivial pls do this so we can provide hyperlinks to organizations that might have taken over a closed location or service
the gogetta fields the need to be eabled for HTML are (only showing the address after the ID string)

- ..../closureInfo and 
-  (tbd, will come back in a minute)

**Comment by jbeard4** [comment]
@adambard1 Can you please provide an example?

**Comment by shakilhossain1** [comment]
fixed

**Comment by doobneek1** [comment]
@shakilhossain1 
![image](https://github.com/user-attachments/assets/282858fe-ea86-44b9-8d30-9a2bb0049139)
not fixed in the list view. Also, please make the hyperlinks underined

**Comment by shakilhossain1** [comment]
we're only seeing this in list page

**Comment by shakilhossain1** [comment]
the hyperlik need to be underlined
